### ISSUE TITLE
socialiteproviders/live should be microsoft-live

### ISSUE THREAD

**Issue by pfeiferchristopher** [SocialiteProviders/socialiteproviders.github.io#10]
Hello,

Should the `composer require socialiteproviders/live` be `microsoft-live`? Because when I did what the website currently has it installed the manager 0.1.10 but `microsoft-live` and the rest of `twitch` etc require manager 1.0.1 which was causing conflicts.

**Comment by DraperStudio** [comment]
Yes, you need to `composer require socialiteproviders/microsoft-live`.

I am currently updating the Providers and wrong docs. Need to do it all solo at the moment so might take a bit but I will update the wrong package names today.

**Comment by pfeiferchristopher** [comment]
I completely understand. Just glad that I could figure out the right one
and get it all working. Thanks!
