### ISSUE TITLE
[Proposal] Simpler & Cleaner Layout

### ISSUE THREAD

**Issue by DraperStudio** [SocialiteProviders/socialiteproviders.github.io#11]
Put together a simpler layout with a bit darker orange since the color started to annoy me and the header was way to big in my opinion.

![screencapture-127-0-0-1-4000-1456230635342](https://cloud.githubusercontent.com/assets/15245398/13251642/c8401288-da31-11e5-9201-fa9b699e6975.png)

**Comment by AndyWendt** [comment]
Looks cool to me.  The syntax highlighting looks good as well.  Let's do it

**Comment by DraperStudio** [comment]
Alright, will clean up the files and push it within the next few days.
