### ISSUE TITLE
Microsoft Live provider is "live" not "microsoft live"

### ISSUE THREAD

**Issue by igorsantos07** [SocialiteProviders/socialiteproviders.github.io#15]
This doc error caused a small confusion that, for a newbie, was quite hard to debug (deep in the code).
I was going to provide a PR but it seems that part is autogenerated, so.. I have no idea how to start :|

Example of the wrong piece:

>**USAGE**
>
>You should now be able to use it like you would regularly use Socialite (assuming you have the facade installed):
>```
>return Socialite::with('microsoft live')->redirect();
>```

**Comment by DraperStudio** [comment]
There is a `socialite_name` variable in the provider.yml which you could use.

The change would need to be done in this file https://github.com/SocialiteProviders/socialiteproviders.github.io/blob/master/_includes/provider/_usage.md

Either send a PR or wait for a fix, this isn't to urgent so it might take a few.

**Comment by igorsantos07** [comment]
Your guidance helped a lot! :)

1. I noticed `socialite_name` is a variable that might not have been set in case the provider does not include it. Will fix in PR and use that.
2. it seems `provider_key` should be used there, instead. Google+ suffers from the same issue (it's `google` instead of `google+`).

**Comment by DraperStudio** [comment]
@igorsantos07 https://github.com/SocialiteProviders/socialiteproviders.github.io/commit/1aab1ab4ac083b5a48836eb91c426cceddc709c3
