### ISSUE TITLE
yiban Oauth2.0 composer package for socialiteproviders

### ISSUE THREAD

**Issue by orochizzzzzzz** [SocialiteProviders/socialiteproviders.github.io#22]
I make a yiban.cn Oauth2.0 composer package for socialiteproviders and it works fine ,but I don't have right to published it in packagist.org.
https://github.com/gdoulingwo/yiban Here is the code,please published it in packagist.org,thanks.

**Comment by faustbrian** [comment]
https://github.com/SocialiteProviders/Yiban
