### ISSUE TITLE
Okta Socialite Provider

### ISSUE THREAD

**Issue by durancu** [SocialiteProviders/socialiteproviders.github.io#27]
I was using tequilarapido/socialite-okta to implement okta provider with Laravel 5.2 since there is no official okta provider in socialiteproviders repository.
Now I am using Laravel 5.5, and they didn't update their plugin since 11 months ago. Can you create an Okta socialite provider, or recommend an updated one??
Thanks in advanced

**Comment by faustbrian** [comment]
Feel free to send a PR for a new Provider to https://github.com/SocialiteProviders/Providers.
