### ISSUE TITLE
Zendesk Socialite Provider Docs

### ISSUE THREAD

**Issue by iamface** [SocialiteProviders/socialiteproviders.github.io#33]
I have just successfully integrated the **Zendesk** Socialite provider. However, the docs at http://socialiteproviders.github.io/providers/zendesk/ are missing one item for the **services config**.

For the Zendesk provider, the other item that needs to be added for the config is:
```
'zendesk' => [
        ...
        'subdomain' => {your_subdomain},
    ],
```

I would happily add a pull request for this fix, but I notice the docs are being created from a blob of https://github.com/SocialiteProviders/socialiteproviders.github.io/blob/master/_includes/provider/installation/_services_and_env.md.

How would you suggest updating this without affecting other provider docs?

Thanks!

**Comment by faustbrian** [comment]
This should work https://github.com/SocialiteProviders/socialiteproviders.github.io/blob/master/_data/providers.yml#L590-L599
